--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PJZ9n/PluginGenerator
build-by-default: true
branches:
  - master
projects:
  PluginGenerator:
      - src: CortexPE/Commando/Commando
        version: 2.1.1
...
